server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: org.silvercloud.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: silvercloud-dept
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloudDB01?characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    # using Hikari
    hikari:
      autoCommit : true
      connectionTestQuery : "select 'x'"
      connectionTimeout : 30000
      idleTimeout : 600000
      initializationFailTimeout : 1
      maxLifetime : 1800000
      maximumPoolSize : 10
      minimumIdle : 1
      validationTimeout : 5000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  cloud:
    inetutils:
      preferred-networks: 192.168.2.   #多网卡选择

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true      #访问路径可以显示IP地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #2.0版本 变量取代了 spring.cloud.client.ipAddress
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html   #swagger2文档 

logging:
  config: classpath:log4j2.xml
  
# 以下是 actuator监控信息的配置 
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,info,health 
info:
  app.name: silvercloud
  company.name: org.silvercloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$


# swagger密码
#security:
#  basic:
#    enabled: true
#    path: /swagger-ui.html
#  user:
#    name: admin
#    password: admin

