server:
  port: 28080
#hosts 文件 127.0.0.1 zuul28080.com
spring:
  application:
    name: gateway

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: silvercloud-gateway
  company.name: org.silvercloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#路由规则
zuul:
  ignored-services: silvercloud-dept  # "*" 屏蔽全部
  prefix: /api                        #服务地址前缀
  routes:                             #路由
    service-api:
      serviceId: silvercloud-dept     #被映射服务id
      path: /deptservice/**           #映射路径
