spring:
  application:
    name: turbine
server:
  port: 20001
management:
  port: 20011
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

turbine:
  app-config: SILVERCLOUD-DEPT
  cluster-name-expression: new String("default")
  combine-host-port: true
  aggregator:
    cluster-config: default