FROM java:8-jre
MAINTAINER  coolsoul<coolsoul0551@qq.com>

ADD ./target/silvercloud-eureka-7001-1.0-SNAPSHOT.jar /app/
CMD ["java", "-Xmx200m", "-jar", "/app/silvercloud-eureka-7001-1.0-SNAPSHOT.jar"]

EXPOSE 7001