server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: org.silvercloud.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  #不能改，否则会注册成不通的微服务，同一个微服务的多个副本找个必须保持一致
  application:
    name: silvercloud-dept
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.47.51:3306/cloudDB02?characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: root
    # using Hikari
    hikari:
      autoCommit : true
      connectionTestQuery : "select 'x'"
      connectionTimeout : 30000
      idleTimeout : 600000
      initializationFailTimeout : 1
      maxLifetime : 1800000
      maximumPoolSize : 10
      minimumIdle : 1
      validationTimeout : 5000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: silvercloud-dept8002
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: silvercloud
  company.name: org.silvercloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$


logging:
  config: classpath:log4j2.xml

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream